blank_issues_enabled: true
contact_links:
    - name: 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
      url: https://github.com/google/googletest/discussions
      about: 
